foot: fix stupid defaults breaking build on some musl setups
Particularly, this may cause issues with ioctl, thanks to this
thing's usage of -pedantic:

../render.c:2173:46: error: overflow in conversion from 'long unsigned int' to 'int' changes value from '2148037735' to '-2146929561' [-Werror=overflow]

This is harmless, so make it not an error.