Revert "mutter: fix undefined reference to gettid"
This patch was temporarily added to resolve a build failure that required
rebuilding the musl cross compilers.

This reverts commit d9e7fef13f28fa63bb4c50f30ea46dd73ba95b10.