beaglebone-kernel: remove package.
FTBFS due to lack of maintenance, platform isn't working properly
anymore:

In file included from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from /builddir/beaglebone-kernel-3.8.13/linux-3.8.13/include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from include/linux/page-flags.h:8,
                 from kernel/bounds.c:9:
include/linux/compiler-gcc.h:100:1: fatal error: linux/compiler-gcc10.h: No such file or directory
  100 | #include gcc_header(__GNUC__)
      | ^~~~~