freecad: add python3-pyside6-network runtime dependency
This avoids an error message at launch time:

    Could not import QtNetwork -- it does not appear to be installed on your system. Your provider may have a package for this dependency (often called "python3-pyside2.qtnetwork")

This is used (at least) by the addon manager:

    Traceback (most recent call last):
      File "/usr/lib/freecad/Mod/AddonManager/addonmanager_workers_utility.py", line 58, in run
        self.request_id = NetworkManager.AM_NETWORK_MANAGER.submit_unmonitored_get(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NetworkManager' object has no attribute 'submit_unmonitored_get'. Did you mean: 'submit_unmonitored_request'?

is thrown when trying to launch it.

Fixes: https://github.com/void-linux/void-packages/issues/58368

Signed-off-by: Vincent Legoll <vincent.legoll@gmail.com>