nbd: update to 3.27.0
- new version
- move from sourceforge to github
- add gnutls library

-  fix compilation warning, by removing CFLAGS addition:
```
    <command-line>: warning: "PROG_NAME" redefined
    <command-line>: note: this is the location of the previous definition
```

- fix compilation by adding libnl3 which is detected by configure script
  and defines macros modifying the code. Error was:
```
    nbd-client.c: In function 'main':
    nbd-client.c:1723:32: error: implicit declaration of function
    'persist_mode_main' [-Wimplicit-function-declaration]
     1723 |                         return persist_mode_main(index,
            sockfds, flags);
          |                                ^~~~~~~~~~~~~~~~~
```

NETLINK-related compilation problem reported upstream, with a proposed fix:
https://github.com/NetworkBlockDevice/nbd/pull/183