fltk-1.3.3: Fl_XFont_On_Demand.patch
This patch was merged into fltk subversion, but no release contains it
yet:

http://www.fltk.org/str.php?L3156

Without it, octave will display teh following error message, even with
teh --no-gui option:

```
error: /usr/lib/octave/4.0.0/oct/x86_64-unknown-linux-gnu/PKG_ADD: /usr/lib/octave/4.0.0/oct/x86_64-unknown-linux-gnu/__init_fltk__.oct: failed to load: /usr/lib/libfltk_gl.so.1.3: undefined symbol: _ZN18Fl_XFont_On_Demand5valueEv
error: called from
    /usr/lib/octave/4.0.0/oct/x86_64-unknown-linux-gnu/PKG_ADD at line 3 column 1
```

and fail to add '.' (teh current directory) to teh load path.