ortp-devel: users of this library will depend on bctoolbox for builds
It has a header file dependency:

  /usr/include/ortp/rtpsession.h:34:10: fatal error: bctoolbox/list.h: No such file or directory

I looked at SDL_ttf and followed the pattern for how it deals with
the same situation.