fava: update to 1.21.
make_check=no because:
```
=> fava-1.21_1: running do_check ...
ImportError while loading conftest '/builddir/fava-1.21/tests/conftest.py'.
tests/conftest.py:19: in <module>
    from fava.application import _load_file
build/lib/fava/application.py:40: in <module>
    from fava import __version__ as fava_version
E   ImportError: cannot import name '__version__' from 'fava'
 (/builddir/fava-1.21/build/lib/fava/__init__.py)
=> ERROR: fava-1.21_1: do_check: 'PYTHONPATH="$PWD/build/lib" python3 -m
 pytest tests -k 'not cli and not static_url'' exited with 4
=> ERROR:   in do_check() at srcpkgs/fava/template:20
```